backend:
  name: git-gateway
  branch: main

# Media storage
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

# Editor preview
display_url: "https://apelng.github.io/ApelGroup"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "index.html"
        editor:
          preview: true  # Enable live preview
        fields:
          # Basic meta
          - {name: "title", label: "Page Title", widget: "string"}
          
          # Hero Section
          - name: "hero"
            label: "Hero Section"
            widget: "object"
            fields:
              - {name: "title", label: "Main Title", widget: "string"}
              - {name: "subtitle", label: "Subtitle", widget: "string"}
              - {name: "button_text", label: "Button Text", widget: "string"}
              - {name: "background", label: "Background Image", widget: "image"}
          
          # Services Section
          - name: "services"
            label: "Services"
            widget: "object"
            fields:
              - {name: "heading", label: "Section Heading", widget: "string"}
              - name: "items"
                label: "Service Items"
                widget: "list"
                fields:
                  - {name: "icon", label: "Icon Class", widget: "string"}
                  - {name: "title", label: "Service Title", widget: "string"}
                  - {name: "description", label: "Description", widget: "text"}
          
          # About Section
          - name: "about"
            label: "About Section"
            widget: "object"
            fields:
              - {name: "heading", label: "Section Heading", widget: "string"}
              - {name: "content", label: "Content", widget: "markdown"}
              - {name: "image", label: "About Image", widget: "image"}
          
          # Raw HTML Access (hidden by default)
          - name: "raw_html"
            label: "Advanced HTML Editor"
            widget: "hidden"
            default: ""
            required: false